### ISSUE TITLE
Crash with arabic input

### ISSUE THREAD

**Issue by janheinrichmerker** [HeinrichReimer/android-inquiry#4]
Inquiry crashes when used with arabic language.

```
05-15 13:57:34.158 16635-16635/eu.pinpong.equalizer E/SQLiteLog: (1) no such column: ١
05-15 13:57:34.158 16635-16635/eu.pinpong.equalizer D/AndroidRuntime: Shutting down VM
05-15 13:57:34.158 16635-16635/eu.pinpong.equalizer E/AndroidRuntime: FATAL EXCEPTION: main
                                                                      Process: eu.pinpong.equalizer, PID: 16635
                                                                      android.database.sqlite.SQLiteException: no such column: ١ (code 1): , while compiling: SELECT BAND_LEVEL_0, BAND_LEVEL_1, BAND_LEVEL_2, BAND_LEVEL_3, BAND_LEVEL_4, BASS_BOOST_ENABLED, BASS_BOOST_LEVEL, _id, LOUDNESS_ENHANCER_ENABLED, LOUDNESS_ENHANCER_LEVEL, PRESET_NAME, VIRTUALIZER_ENABLED, VIRTUALIZER_LEVEL FROM PRESETS WHERE PRESET_NAME = ? ORDER BY null LIMIT ١
                                                                          at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
                                                                          at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:887)
                                                                          at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:498)
                                                                          at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:588)
                                                                          at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:58)
                                                                          at android.database.sqlite.SQLiteQuery.<init>(SQLiteQuery.java:37)
                                                                          at android.database.sqlite.SQLiteDirectCursorDriver.query(SQLiteDirectCursorDriver.java:44)
                                                                          at android.database.sqlite.SQLiteDatabase.rawQueryWithFactory(SQLiteDatabase.java:1316)
                                                                          at android.database.sqlite.SQLiteDatabase.queryWithFactory(SQLiteDatabase.java:1163)
                                                                          at android.database.sqlite.SQLiteDatabase.query(SQLiteDatabase.java:1034)
                                                                          at android.database.sqlite.SQLiteDatabase.query(SQLiteDatabase.java:1202)
                                                                          at com.afollestad.inquiry.SQLiteHelper.query(SQLiteHelper.java:42)
                                                                          at com.afollestad.inquiry.Query.getInternal(Query.java:147)
                                                                          at com.afollestad.inquiry.Query.one(Query.java:169)
```

_(See the [original issue](https://github.com/afollestad/inquiry/issues/17)) by @pinpong_

**Comment by janheinrichmerker** [comment]
Might be fixable by wrapping all strings passed to the DB with `String.valueOf(Locale.US, "<string here>")`.

**Comment by janheinrichmerker** [comment]
https://github.com/Simperium/simperium-android/commit/3376000617ec43f935b8213185ce14bbed9b7438

**Comment by aitorvs** [comment]
##### Proposed Change

The issue appears when calling `Locale.getDefault()` while checking for `limit` and `offset` values. Just change it to `Locale.US` as follows.

```
if (limit > 0) sort.append(String.format(Locale.US, " LIMIT %d", limit));
if (offset > 0) sort.append(String.format(Locale.US, " OFFSET %d", offset));
```

**Comment by janheinrichmerker** [comment]
Would you mind creating a pull fixing this?
